"""Stickiness, precise event copy, staged injuries, relationship and skill feedback."""
from pathlib import Path
from playwright.sync_api import sync_playwright

root=Path(__file__).resolve().parent.parent
html=(root/'index.html').read_text().replace('<link rel="stylesheet" href="./assets/styles.css">','<style>'+(root/'assets/styles.css').read_text()+'</style>')
scripts=['legacy-rewrites','childhood','later-life','legacy-outcomes','passive-life','career-stories','hobby-world','world-social','personality-world','story-pass','game']
for script in scripts:
    path=f'assets/{script}.js';js=(root/path).read_text()
    if script=='game':
        js=js.replace('startingLook=newLook();load();', '''window.__storyQA={state:()=>s,newGame,save,load,ageUp,byId,makePerson,socialAction,resolveEvent,events,context,statChange,relate,showAnnualEvent,fightStart,passAway};startingLook=newLook();load();''')
    html=html.replace(f'<script src="./{path}"></script>','<script>'+js+'</script>')

with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage'])
    for width in (320,390,768,1024):
        page=browser.new_page(viewport={'width':width,'height':830})
        errors=[];page.on('pageerror',lambda exc:errors.append(str(exc)))
        page.goto('about:blank')
        page.evaluate('''()=>{let cache={};Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>cache[k]||null,setItem:(k,v)=>{cache[k]=v},removeItem:k=>delete cache[k]}})}''')
        page.set_content(html)
        page.evaluate("window.__storyQA.newGame('Frankie Finch','sporty',15)")
        page.locator('.modal [data-modal]').first.click()
        assert page.locator('.top-age-button').count()==1
        assert page.locator('.top-age-button').is_visible()
        # Age Up is in exactly one sticky header on all seven playable pages.
        for section in ('home','activities','people','life','work','tree','journal'):
            page.locator(f'.bottom-nav [data-tab="{section}"]').click()
            assert page.locator('.top-age-button').count()==1,(width,section)
            assert page.locator('.top-age-button').is_visible(),(width,section)
        count=page.evaluate("window.LITTLE_LIFE_STORY_PASS.scenes.length")
        assert count>=17,count
        desc=page.evaluate("__storyQA.events.find(e=>e.id==='friendsecret').text")
        assert 'bake-sale' in desc,desc
        # The old autogenerated options no longer have generic copy-paste outcomes.
        assert not page.evaluate("__storyQA.events.some(e=>/^v4_\\d+$/.test(e.id)&&e.choices.some(c=>(c.bad||'').includes('mixed feelings')||(c.bad||'').includes('longer than expected')))")
        page.locator('.bottom-nav [data-tab="people"]').click()
        page.evaluate('window.scrollTo({top:900,behavior:"instant"})')
        page.wait_for_timeout(100)
        top=page.locator('.top-age-button').bounding_box()
        assert top and -1<=top['y']<=130,(width,top)
        page.evaluate('''()=>{const q=__storyQA,x=q.state();x.age=15;x.energy=3;x.skills.sports=70;const person=q.makePerson('Felix Navarro',x.year-15,[],'friend');person.bonds[x.playerId]=45;q.save();q.socialAction(person.id,'fight');}''')
        assert page.locator('.modal').get_by_text('Felix Navarro').count()>=1
        assert page.locator('.modal [data-modal]').count()==4
        assert page.locator('.top-age-button').is_disabled()
        page.locator('.modal [data-modal]').nth(3).click()  # First punch: first of two stages
        assert page.locator('.modal [data-modal]').count()==3
        before=page.evaluate('''()=>({bond:__storyQA.byId(__storyQA.state().activeFight.opponent).bonds[__storyQA.state().playerId],energy:__storyQA.state().energy})''')
        page.locator('.modal [data-modal]').nth(2).click()
        ending=page.evaluate('''()=>{const q=__storyQA,x=q.state(),f=x.fightHistory.at(-1);return {finished:!x.activeFight,rounds:f.rounds.length,aggressive:f.aggressive,bond:q.byId(f.opponent).bonds[x.playerId],energy:x.energy,health:x.stats.health,history:x.history.some(h=>h.kind==='fight'),memory:x.promises.some(p=>p.title.includes('Felix'))}}''')
        assert ending['finished'] and ending['rounds']==2 and ending['aggressive'],ending
        assert ending['bond']<before['bond'] and ending['energy']==before['energy'],ending
        assert ending['history'] and ending['memory'],ending
        page.locator('.impact-chip').first.wait_for(timeout=3000);assert page.locator('.impact-chip').count()>0
        assert any('Felix' in t for t in page.locator('.impact-chip').all_text_contents()),page.locator('.impact-chip').all_text_contents()
        assert page.locator('.top-age-button').is_enabled()
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth'),f'overflow {width}'
        page.evaluate("document.querySelector('[data-close]')?.click();document.querySelector('[data-do=theme]')?.click()")
        assert page.evaluate("document.documentElement.getAttribute('data-theme')")=='dark'
        assert page.locator('.top-age-button').is_visible()
        assert not errors,(width,errors)
        print('STORY/COMBAT PASS',width,{'stories':count,'rounds':ending['rounds'],'rivalBond':ending['bond'],'feedback':page.locator('.impact-chip').count()})
        page.close()
    browser.close()